<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 根工程本身只是一个聚合器 -->
    <groupId>jh.exp</groupId>
    <artifactId>exp_v2</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <modules>
        <module>exp-common</module>
        <module>exp-gateway</module>
        <module>exp-auth</module>
        <module>exp-bid-contract</module>
        <module>exp-project</module>
        <module>exp-corp</module>
        <module>exp-dependency</module>
        <module>exp-corp/exp-corp-client</module>
        <module>exp-corp/exp-corp-core</module>
        <module>exp-corp/exp-corp-service</module>
        <module>exp-project/exp-project-client</module>
        <module>exp-project/exp-project-core</module>
        <module>exp-project/exp-project-service</module>
        <module>exp-gateway/exp-gateway-client</module>
        <module>exp-gateway/exp-gateway-core</module>
    </modules>
</project>