<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>jh.exp.bid-contract</groupId>
        <artifactId>exp-bid-contract</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>exp-bid-contract-service</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- 招标服务客户端，包含HTTP客户端定义和自动配置 -->
        <dependency>
            <groupId>jh.exp.bid-contract</groupId>
            <artifactId>exp-bid-contract-core</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jh.exp.auth</groupId>
            <artifactId>exp-auth-client</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>jh.exp.auth</groupId>
            <artifactId>exp-auth-core</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jh.exp.corp</groupId>
            <artifactId>exp-corp-client</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>jh.exp.corp</groupId>
            <artifactId>exp-corp-core</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>jh.exp.project</groupId>
            <artifactId>exp-project-client</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>jh.exp.project</groupId>
            <artifactId>exp-project-core</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>jh.exp.sys</groupId>
            <artifactId>exp-sys-client</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Spring Cloud LoadBalancer，用于服务发现和负载均衡 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
    </dependencies>

</project>